import { Inter } from "next/font/google";
import "./globals.css";
import GameProvider from "@/context/game-context";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Game 2048",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body suppressHydrationWarning className={inter.className}>
        <GameProvider>{children}</GameProvider>
      </body>
    </html>
  );
}
